### ISSUE TITLE
App creates token without a scope even when the `options.defaultScopes` is set to `["repo"]`

### ISSUE THREAD

**Issue by ed42311** [octokit/oauth-app.js#110]
Hope I'm doing something silly here and it will be easy to spot

Here is the code:  https://github.com/ed42311/github-new-repo

Not sure if there is a better way to present this, might be a bit much to test run, if you clone, install and `yarn start`
Oh you'll need to create an OAuth app and put CLIENT_ID and CLIENT_SECRET in a `.env`

Here is the flow:
1. Click the link in `localhost:8080`
2. OAuth app does it's thing and returns access token
3. Octokit instance is authorized
4. `octokit.repos.createForAuthenticatedUser` creates a hello_world repo

I've tried the last action with a personal access token and it works, but through the auth flow I'm obviously missing something.
Querying for the access token:
```typescript
    const tokenResponse = await axios({
      method: 'post',
      url: `https://github.com/login/oauth/access_token?client_id=${CLIENT_ID}&client_secret=${CLIENT_SECRET}&code=${requestToken}&scope=user%20public_repo%20repo`,
      headers: {
        accept: 'application/json',
      },
    })
 const accessToken = tokenResponse.data.access_token
```
then 
```typescript
    const octokit = new Octokit({ auth: accessToken })
    const response = await octokit.repos.createForAuthenticatedUser({
      name: 'hello_world',
    })
```
response errors out in the trycatch
```sh
RequestError [HttpError]: Not Found
    at /Users/contextcue/code/experiments/node-oauth-example/node_modules/@octokit/request/dist-node/index.js:66:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /Users/contextcue/code/experiments/node-oauth-example/dist/index.js:39:26 {
  status: 404,
  headers: {
    'access-control-allow-origin': '*',
    'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset',
    connection: 'close',
    'content-encoding': 'gzip',
    'content-security-policy': "default-src 'none'",
    'content-type': 'application/json; charset=utf-8',
    date: 'Fri, 24 Jul 2020 18:10:10 GMT',
    'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
    server: 'GitHub.com',
    status: '404 Not Found',
    'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
    'transfer-encoding': 'chunked',
    vary: 'Accept-Encoding, Accept, X-Requested-With',
    'x-accepted-oauth-scopes': 'public_repo, repo',
    'x-content-type-options': 'nosniff',
    'x-frame-options': 'deny',
    'x-github-media-type': 'github.v3; format=json',
    'x-github-request-id': 'CEA1:2742:1C206:431AD:5F1B2402',
    'x-oauth-client-id': '093b90a514074765c4d8',
    'x-oauth-scopes': '',
    'x-ratelimit-limit': '5000',
    'x-ratelimit-remaining': '4996',
    'x-ratelimit-reset': '1595617064',
    'x-xss-protection': '1; mode=block'
  },
  request: {
    method: 'POST',
    url: 'https://api.github.com/user/repos',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit-rest.js/18.0.2 octokit-core.js/3.1.1 Node.js/14.6.0 (darwin; x64)',
      authorization: 'token [REDACTED]',
      'content-type': 'application/json; charset=utf-8'
    },
    body: '{"name":"hello_world"}',
    request: { hook: [Function: bound bound register] }
  },
  documentation_url: 'https://developer.github.com/v3/repos/#create'
}
```
noticed that scopes are blank, so maybe I need to format scopes differently?  I've seen both `scopes` and `scope` used and tried both but no dice.

**Comment by gr2m** [comment]
It worked :tada:

https://github.com/gr2m-test/hello_world

**Comment by ed42311** [comment]
@gr2m OMG I thought the zombies got you!  Thanks yo, timing is impeccable as well, got all the other stuff I needed finished up last week.  Cheers :beers:

**Comment by nayebare** [comment]
@ed42311 and @gr2m i found the repository empty. [https://github.com/gr2m-test/hello_world)]. However i would appreciate if you guided me through this. Thank you.
@gr2m help needed please. In trying to access the GITHUB API through the octokit. The GET method is successful but the POST method is not successful via the code. It is only successfully through POST man. Here is my code. Any help is appreciated. Thank you.
`    let octokit = new Octokit({
auth: process.env.GITHUB_TOKEN
    })

    //
    // To create milestones in a repository
    //
    let response = await octokit.request("GET /repos/{owner}/{repo}/milestones",{
            owner: "EcoDevHackathon",
            repo: repo_name,
            title: 'v545344.0',
            state: 'open',
            description: 'Tracking milestone for version 1.0',
            due_on: '2012-10-09T23:39:01Z'
        })`
Response:
```
  data: [
    {
      url: 'https://api.github.com/repos/EcoDevHackathon/midimar/milestones/7',
      html_url: 'https://github.com/EcoDevHackathon/midimar/milestone/7',
      labels_url: 'https://api.github.com/repos/EcoDevHackathon/midimar/milestones/7/labels',
      id: 8489504,
      node_id: 'MI_kwDOCGlzcM4AgYog',
      number: 7,
      title: 'v56573.0',
      description: 'Tracking milestone for version 2.0',
      creator: [Object],
      open_issues: 0,
      closed_issues: 0,
      state: 'open',
      created_at: '2022-10-03T10:08:47Z',
      updated_at: '2022-10-03T10:08:47Z',
      due_on: '2012-10-09T07:00:00Z',
      closed_at: null
    }
  ]
```
Code in the POST request:
`    let octokit = new Octokit({
  auth: process.env.GITHUB_TOKEN
    })

    //
    // To create milestones in a repository
    //
    let response = await octokit.request("POST /repos/{owner}/{repo}/milestones",{
            owner: "EcoDevHackathon",
            repo: repo_name,
            title: 'v545344.0',
            state: 'open',
            description: 'Tracking milestone for version 1.0',
            due_on: '2012-10-09T23:39:01Z'
        })`

Response from POST request:
  ```
  data: {
      message: 'Not Found',
      documentation_url: 'https://docs.github.com/rest/reference/issues#create-a-milestone'
    }
  },
  request: {
    method: 'POST',
    url: 'https://api.github.com/repos/EcoDevHackathon/midimar/milestones',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit-rest.js/19.0.4 octokit-core.js/4.0.5 Node.js/16.0.0 (linux; x64)',
      'content-type': 'application/json; charset=utf-8'
    },
    body: '{"title":"v545344.0","state":"open","description":"Tracking milestone for version 1.0","due_on":"2012-10-09T23:39:01Z"}',
    request: { hook: [Function: bound bound register] }
  }
```

**Comment by timrogers** [comment]
@nayebare Could you please stick to one issue? We're also discussing this in https://github.com/octokit/core.js/issues/254#issuecomment-1265427708.

**Comment by nayebare** [comment]
Thank you @timrogers , you are surely a saver, i had not realized that my .env does not work because the GET request was working. The code now works. Thanks a lot. Its good to have another pair of eyes, I have removed the the other issue.

**Comment by nayebare** [comment]
hey @timrogers  is it possible to set the same milestone for multiple repositories?

**Comment by timrogers** [comment]
I'm afraid I don't know - sorry! You'd be best off checking the docs and asking the support team if you're not sure.

**Comment by nayebare** [comment]
Great, thanks @timrogers  will do that.

**Comment by nayebare** [comment]
Hey @timrogers, why can't update a milestone with lower milestone number via the Github API. I have two milestones under one repository,  /milestone/11 & /milestone/14. This is the server response for milestone number 11.
`{
  status: 200,
  url: '/milestones/11',
  headers: { //removed
  },
  data: {
    url: '/milestones/11',
    html_url: '/milestone/11',
    labels_url: '/milestones/11/labels',
    id: 8536245,
    node_id: 'MI_kwDOIE8bH84AgkC1',
    number: 11,
    title: 'vr1.0.5',
    description: 'my cool update',
    creator: {
  //removed
    },
    open_issues: 0,
    closed_issues: 0,
    state: 'open',
    created_at: '2022-10-13T10:07:57Z',
    updated_at: '2022-10-13T12:02:38Z',
    due_on: '2022-10-20T07:00:00Z',
    closed_at: null
  }
}`
And here is the output when i run milestone number 14
RequestError [HttpError]: Validation Failed: {"resource":"Milestone","code":"already_exists","field":"title"}
    at /node_modules/@octokit/request/dist-node/index.js:88:21
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /testing.js:125:28 {
  status: 422,
  response: {
    url: '/milestones/14',
    status: 422,
    headers: {
 //removed
    },
    data: {
      message: 'Validation Failed',
      errors: [Array],[ { resource: 'Milestone', code: 'already_exists', field: 'title' } ]
      documentation_url: '/reference/issues#update-a-milestone'
    }
  },
  request: {
    method: 'PATCH',
    url: '/milestones/14',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit-core.js/4.0.5 Node.js/16.0.0 (linux; x64)',
      authorization: 'token [REDACTED]',
      'content-type': 'application/json; charset=utf-8'
    },
    body: '{"title":"vr1.0.5","state":"open","description":"my cool update","due_on":"2022-10-20T23:39:01Z"}',
    request: { hook: [Function: bound bound register] }
  }
}
