### ISSUE TITLE
How to handle user sessions?

### ISSUE THREAD

**Issue by chopfitzroy** [octokit/oauth-app.js#183]
I think I might be living into a bit of an anti pattern here or at the very least over complicating so please let me know if I am missing something obvious.

I have an Express API that is using `oauth-app.js` (middlewares are so nice BTW 🎉) and I have two different React UI's that hit this API based on different things (one helps create a PR one helps to create an issue) I am struggling with two things.

1) ~~Based on which UI the user came from I want to send them back to the right UI via the `oauth` callback URL. now from what I can see the `state` parameter mentioned [here](https://github.com/octokit/oauth-app.js#appcreatetokenoptions) looks like it might work so I am going to try for an implementation with that.~~ I misunderstood [redirect URL's](https://docs.github.com/en/free-pro-team@latest/developers/apps/authorizing-oauth-apps#redirect-urls) and now realize this is the right approach.

2) How do I maintain a "session" between the two UI's or even with multiple people hitting the API from one UI, based on my understanding there is essentially one `app` instance that is updated on every event i.e:

```js
app.on("token", async ({ token, octokit }) => {
  const { data } = await octokit.request("GET /user");
  console.log(`Token retrieved for ${data.login}`);
});
```

Would this mean I need to essentially create an instance of `app` for each user session I have? (being completely honest I am new-ish to server side and the notion of sessions has always confused me) or would it simply be better to associate each `token` with each user session and create my own `octokit` instances as needed with the token added to the headers?

**UPDATE** After reading this [probot post](https://jasonet.co/posts/probot-with-ui/) I realize I was approaching this wrong and thinking of how I would make sessions work with the pre existing middleware routes, when instead I need to write my own routes, as for the `octokit` instance it looks like updating this based on the session token will be the way to go.

**Comment by chopfitzroy** [comment]
Closing as I am pretty sure this is the right approach after some further reading I was just approaching from the wrong angle.

**Comment by gr2m** [comment]
> ```js
> ```js
> app.on("token", async ({ token, octokit }) => {
>   const { data } = await octokit.request("GET /user");
>   console.log(`Token retrieved for ${data.login}`);
> });
> ```
> 
> 
> Would this mean I need to essentially create an instance of app for each user session I have? (being completely honest I am new-ish to server side and the notion of sessions has always confused me) or would it simply be better to associate each token with each user session and create my own octokit instances as needed with the token added to the headers?
> ```

The `octokit` parameter in the example you quoted is an instance specific to this token, so yes, I'd create a new octokit instance for each session/token.

Thank you for sharing your struggle, I'm also figuring this out right now, there are not a lot of projects out there we can learn from. I think the OAuth flow is especially for front-end developers who want to use custom UIs for GitHub and/or want to use GitHub as backend for authorization and data. 

I hope to eventually provide a hosted version of `@octokit/oauth-app`, so you don't need to worry about a backend at all, you can just built a static front-end. What I usually do for sessions is to store the GItHub token using browser storage (localStorage or IndexedDB). Just beware that if you host your static frontend on a shared host such as `[your username].github.io`, then other apps on the same host will be able to access the same browser storage

**Comment by chopfitzroy** [comment]
> I hope to eventually provide a hosted version of @octokit/oauth-app, so you don't need to worry about a backend at all, you can just built a static front-end. What I usually do for sessions is to store the GItHub token using browser storage (localStorage or IndexedDB).

This would be absolutely AMAZING 🎉

I will share whatever implementation I end up with here so anyone who finds this issue can use it for reference if they choose to.
