### ISSUE TITLE
Updating documentation links.

### ISSUE THREAD

**Issue by chopfitzroy** [octokit/oauth-app.js#184]
**What’s missing?**

Currently links appear to point to the old documentation i.e:
- https://developer.github.com/enterprise/2.16/apps/building-oauth-apps/authorizing-oauth-apps/#redirect-urls
Instead of:
- https://docs.github.com/en/free-pro-team@latest/developers/apps/authorizing-oauth-apps#redirect-urls

**Why?**
I wanted to see if this was intentional before I open a PR to resolve.

**Alternatives you tried**
N/A

**Comment by gr2m** [comment]
not intentional, thank you for bringing it up. Pull request welcome!
