### ISSUE TITLE
Handle callback errors

### ISSUE THREAD

**Issue by gr2m** [octokit/oauth-app.js#2]
**What’s missing?**

If an authorization error occurs, the callback redirect has different query parameters. Example

```
?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23redirect-uri-mismatch
```

**Why?**

It's a standard error behavior of GitHub's API and should be covered by Octokit

**Comment by copperwall** [comment]
Hey @gr2m  👋 I'd be up to try implementing this if that's cool with you

**Comment by gr2m** [comment]
Absolutely!
