### ISSUE TITLE
Is this package going to work after Github's sunsetting?

### ISSUE THREAD

**Issue by GiladFeder** [octokit/oauth-app.js#258]
Specifically, I am talking about https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param/
I am considering using this package but unsure due to the confusing message regarding deprecation of using clientId + clientSecret, which is similar to the main example of:

```
const app = new OAuthApp({
  clientType: "oauth-app",
  clientId: "1234567890abcdef1234",
  clientSecret: "1234567890abcdef1234567890abcdef12345678",
});
```

**Comment by gr2m** [comment]
Yes, this package is not affected by GitHub's sunsetting of the query parameters because we send the credentials in the `Authorization` header.
