### ISSUE TITLE
`const { octokit } = await app.getUserOctokit({ code, state });` not working as expected

### ISSUE THREAD

**Issue by ganning127** [octokit/oauth-app.js#259]
**What happened?**
When authenticating octokit using the [docs](https://github.com/octokit/oauth-app.js#appgetuseroctokitoptions):

```js
const { octokit } = await app.getUserOctokit({ code: "code123" });
```

would always return that `octokit` was undefined, so I tried doing 

```js
const octokit = await app.getUserOctokit({ code: "code123" });
```

and that gave me an `octokit` instance that I was able to use. 

**What did you expect to happen?**
```js
const { octokit } = await app.getUserOctokit({ code: "code123" });
```
should return a valid instance of `octokit`, but it does not, so we could change the docs to say:

```js
const octokit = await app.getUserOctokit({ code: "code123" });
```

**The code that worked for me**
```js
 const app = new OAuthApp({
        clientType: "oauth-app",
        clientId: process.env.CLIENT_ID,
        clientSecret: process.env.CLIENT_SECRET,
        defaultScopes: "repo"
});

const octokit = await app.getUserOctokit({ code, state });
```

**Comment by gr2m** [comment]
> we could change the docs to say:
> 
> ```js
> const octokit = await app.getUserOctokit({ code: "code123" });
> ```

Agreed! Thank you for reporting the issue. Would you like to send a pull request to fix the documentation?
