### ISSUE TITLE
Remove Node version 10 from .github/workflows/test.yml

### ISSUE THREAD

**Issue by oscard0m** [octokit/oauth-app.js#299]
# Description
Node v10 has been deprecated so there is no need to keep giving support to it in our CI.
# Context
You can find more details [here](https://github.com/orgs/octokit/teams/js-community/discussions/6)

**Comment by timrogers** [comment]
👋 I am in favour of making this change across the JS repos, but I think we might want to release the change as a major version, given that we will no longer guarantee Node 10.x comparability. What do you think?

**Comment by oscard0m** [comment]
> 👋 I am in favour of making this change across the JS repos, but I think we might want to release the change as a major version, given that we will no longer guarantee Node 10.x comparability. What do you think?

👋🏽 @timrogers!

I'm not sure about making it a major version. 

Since the published code is not changing (we only stop checking if it works with `Node 10`), technically people can safely upgrade with no change in their applications, right?

On the other hand, there is this intention to stop giving support to `Node 10` so I'm not sure what is the proper approach in this case.

**Comment by timrogers** [comment]
I definitely agree that this is a tricky case.  The code is not changing, but I still think it is significant. 

Right now, our CI checks guarantee that Node 10 will work. With this change, we provide no guarantees. Node 10 could break at any time and we'd have no way of knowing or communicating that. 

My preference is to "play it safe" and go for a major version to avoid surprises. People will see the release notes and will know if Node 10 matters to them. 

@gr2m @nickfloyd What do you think? ❤️

**Comment by timrogers** [comment]
@oscard0m And, of course, I'm interested to hear what you think too! ✨

**Comment by wolfy1339** [comment]
When stopping support for a node version, it's definitely a major change.

See this comment on a PR I made to drop support for NodeJS v10 https://github.com/octokit/webhooks.js/pull/555#issuecomment-827946357

**Comment by oscard0m** [comment]
> @oscard0m And, of course, I'm interested to hear what you think too! ✨

I'm up for releasing a major version.

I was wondering, for NodeJS 12 we would do a different major version or we want to drop support for both in the same breaking changes?

**Comment by timrogers** [comment]
> > @oscard0m And, of course, I'm interested to hear what you think too! ✨
> 
> 
> 
> I'm up for releasing a major version.
> 
> 
> 
> I was thinking, for NodeJS 12 we would do a different major version or do we want to drop support for both in the same breaking changes?

If we want to drop support for deprecated Node versions, I think we should do multiple together in one go. 

It's the same logical change: dropping support for end-of-life Node releases.

**Comment by wolfy1339** [comment]
I have started an octoherd script to deal with the required changes: https://github.com/wolfy1339/octoherd-script-remove-eol-node-versions/pull/1
