### ISSUE TITLE
Regression introduced in v3.6.3

### ISSUE THREAD

**Issue by wolfy1339** [octokit/oauth-app.js#308]
**What happened?**

While upgrading the dependency in https://github.com/octokit/app.js/pull/306 due to the dropping of NodeJS v10 and v12 support, the tests failed
**What did you expect to happen?**

The tests to not have failed

**What the problem might be**

The regression was introduced by #288

/cc @baoshan

**Comment by wolfy1339** [comment]
> We can publish a revert to both v4 and v3

@wolfy1339 Do you know what was the expected output here? https://github.com/octokit/oauth-app.js/pull/288
a) Get rid of `state` property
b) Make `state` property optional (only pass it if defined)

_Originally posted by @oscard0m in https://github.com/octokit/app.js/issues/306#issuecomment-1179125684_

**Comment by baoshan** [comment]
Please see my preliminary thoughts on #309.
