### ISSUE TITLE
Stop pulling in `aws-lambda` which pulls in the huge `aws-sdk`

### ISSUE THREAD

**Issue by voxpelli** [octokit/oauth-app.js#330]
**What’s missing?**

This module itself with all non-optional dependencies is [quite small](https://bundlephobia.com/package/@octokit/oauth-app@4.0.7) compared to the size of `aws-lambda` and its dependencies, which is [+44x the size](https://bundlephobia.com/package/aws-lambda@1.0.7).

Since optional dependencies are installed by default and there's no simple way of opting out of specific optional dependencies the change in #283 made most users of this module (and in turn the users of `octokit`) pull in `aws-lambda` and in turn `aws-sdk`, which is likely going to be the heaviest of all the modules in their `node_modules` folder.

**Why?**

If `aws-lambda` needs to be included as a dependency, then make it so that it will only actively be pulled in by those actively wanting it and avoid the drive-by adding of the `aws-lambda`/`aws-sdk` to everyone else.

**Alternatives you tried**

I did try `npm ci --no-optional` and that worked, but also causes all optionals to be opt outed from, not just this one, and it was very easy to miss that it would help this nested behemoth from being pulled in.

**Comment by oscard0m** [comment]
✅ Removed `aws-lambda` as a dependency of the project but still pending decoupling it from `@types/aws-lambda`.

With this change we have reduced considerably the install size:

|   | Publish size | Install size |
|---|--------------|--------------|
| @octokit/oauth-app@4.0.7[^1] | 153kB | 82.6MB |
| @octokit/oauth-app@4.0.8[^2] | 153kB | 6.48MB |

[^1]: https://packagephobia.com/result?p=@octokit/oauth-app@4.0.7
[^2]: https://packagephobia.com/result?p=@octokit/oauth-app@4.0.8

<img width="851" alt="image" src="https://user-images.githubusercontent.com/2574275/187557892-c223f255-75ad-43b5-ba86-f3edf9e7740e.png">

You can subscribe to this issue to follow up on the removal of `@types/aws-lambda`: https://github.com/octokit/oauth-app.js/issues/332

I hope this has removed some friction already.
