### ISSUE TITLE
[BUG]: Using `oauth.allowSignup: false` has no effect while using `createNodeMiddleware`

### ISSUE THREAD

**Issue by SayakMukhopadhyay** [octokit/oauth-app.js#369]
### What happened?

When I am using `createNodeMiddleware` I noticed that the authorization URL is using `allowSignup` as `true` by default. In order to disable that I added `oauth.allowSignup: false` in the App options as such
```js
function setupGitHub() {
  return new App({
    appId: process.env.GITHUB_APP_ID!,
    privateKey: readFileSync(process.env.GITHUB_KEY!, 'utf8'),
    webhooks: {
      secret: process.env.GITHUB_WEBHOOK_SECRET!
    },
    oauth: {
      clientId: process.env.GITHUB_CLIENT_ID!,
      clientSecret: process.env.GITHUB_CLIENT_SECRET!,
      allowSignup: false,
      redirectUrl: process.env.GITHUB_REDIRECT_URL
    }
  })
}
```
But this had no effect.

This seems to me because I didnt add the `allowsignup` parameter to the `login` request. The relevant line where the bug is happening is https://github.com/octokit/oauth-app.js/blob/728b032e3c6233350bb76744e5940c28d9cba01e/src/methods/get-web-flow-authorization-url.ts#L24
and the `options.allowSignup` in the above line is true because
https://github.com/octokit/oauth-app.js/blob/728b032e3c6233350bb76744e5940c28d9cba01e/src/middleware/handle-request.ts#L79
and `query.allowSignup !== "false"` evaulates to `true` if the login request doesn't contain the `allowSignup` parameter.

### Versions

Octokit.js@2.0.10 and @octokit/oauth-app@4.1.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gr2m** [comment]
Would you like to try and send a pull request? You can start out by creating a failing test that replicates the bug. The test would go in this file: https://github.com/octokit/oauth-app.js/blob/master/test/node-middleware.test.ts

**Comment by SayakMukhopadhyay** [comment]
Yeah, I am creating a PR for the same.
