### ISSUE TITLE
[DOCS]: Is there any way to use this without clientSecret?

### ISSUE THREAD

**Issue by giovanni-bertoncelli** [octokit/oauth-app.js#504]
### Describe the need

I'd like to know if there any way to use this plugin without specifying a clientSecret. My use case is a CLI that cannot have a clientSecret hardcoded and should use some Oauth Flow (Authorization Code + PKCE?) with only client id.
By simply not specifying the clientSecret I get always an error like this:

```
{"error":"The client_id and/or client_secret passed are incorrect. (incorrect_client_credentials, https://docs.github.com/apps/managing-oauth-apps/troubleshooting-oauth-app-access-token-request-errors/#incorrect-client-credentials)"}
```

### SDK Version

@octokit/oauth-app@6.1.0

### Relevant log output

```shell
{"error":"The client_id and/or client_secret passed are incorrect. (incorrect_client_credentials, https://docs.github.com/apps/managing-oauth-apps/troubleshooting-oauth-app-access-token-request-errors/#incorrect-client-credentials)"}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wolfy1339** [comment]
Maybe the OAuth device flow is more suited for your needs?
https://github.com/octokit/auth-oauth-device.js/

**Comment by giovanni-bertoncelli** [comment]
Yes, that's probably it! Thank you!
