### ISSUE TITLE
[BUG]: Delete token fails using middleware

### ISSUE THREAD

**Issue by Sammy-T** [octokit/oauth-app.js#541]
### What happened?

I have a project set up to use `createWebWorkerHandler` on Cloudflare Pages Functions. It works to get a user token but when I attempt a DELETE request to `/api/github/oauth/token` using the same token, I get a `Not Found` error. 

The token is valid and I'm able to make other requests with it. I'm also able to delete the token by directly making a request to the REST api as shown in the [docs](https://docs.github.com/en/rest/apps/oauth-applications?apiVersion=2022-11-28#delete-an-app-token) but I'm unable to get it working using the middleware.

I've tried including the user token as a Bearer auth header and I've tried including the client_id and access_token as json in the request body.

The script implementing the middleware:

```js
// functions/api/github/oauth/[[path]].js

import { OAuthApp, createWebWorkerHandler } from '@octokit/oauth-app';

export async function onRequest(context) {
    const { env, request } = context;

    const app = new OAuthApp({
        clientType: env.CLIENT_TYPE,
        clientId: env.CLIENT_ID,
        clientSecret: env.CLIENT_SECRET
    });

    const handleRequest = createWebWorkerHandler(app);

    return handleRequest(request);
}
```

### Versions

Node v18.19.1, @octokit/oauth-app v7.1.3

### Relevant log output

```shell
{
  "error": "Not Found - https://docs.github.com/rest/apps/oauth-applications#delete-an-app-token"
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Sammy-T** [comment]
I found this line while trying to trace back what was going on:

https://github.com/octokit/oauth-app.js/blob/a8d5e253b0b3cfed0b3684e7c5bb69120e46c906/src/middleware/handle-request.ts#L259

So apparently the expected auth header is

```http
Authorization: token [token]
```

but I was using 

```http
Authorization: Bearer [token]
```

I'm glad I'm able to get this to work now but shouldn't it be a Bearer token?

**Comment by gr2m** [comment]
I think the `Bearer` prefix is only used for JSON Web Token authentication by GitHub Apps, everywhere else the `token` prefix is used. But I've seen both working at places 🤷 

Just for our understanding, were you able to resolve the problem in your code, or is there still something we should address in this module?

**Comment by Sammy-T** [comment]
Ok, I wish I understood why but thanks for the reply. 

My issue was that I'm used to working with the `Bearer` prefix on various platforms but I'd never seen the `token` prefix before and it wasn't clear to me from the README that `token` is the expected prefix.

But yes, I've got it working now so I'll close this issue.
